# Generated by Django 5.1.2 on 2024-10-23 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_batik', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('asal_usul', models.TextField()),
                ('makna', models.TextField()),
                ('foto', models.ImageField(upload_to='gallery/batik_images/')),
            ],
        ),
    ]
